version: "2.1"
x-logger: &logger
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
x-common: &common
  image: darkatse/script-docker:latest
  restart: always
services:
  script-docker-1:
    <<: [ *logger, *common ]
    container_name: script-docker-1
    build:
      context: .
      dockerfile: ./Dockerfile
      args: 
        env_count: 1
    volumes:
      - ./scripts:/sripts_colle
      - ./env/all:/all
      - ./env/env1:/env
  script-docker-2:
    <<: [ *logger, *common ]
    container_name: script-docker-2
    build:
      context: .
      dockerfile: ./Dockerfile
      args: 
        env_count: 2
    volumes:
      - ./scripts:/sripts_colle
      - ./env/all:/all
      - ./env/env2:/env
  script-docker-3:
    <<: [ *logger, *common ]
    container_name: script-docker-3
    build:
      context: .
      dockerfile: ./Dockerfile
      args: 
        env_count: 3
    volumes:
      - ./scripts:/sripts_colle
      - ./env/all:/all
      - ./env/env3:/env
  script-docker-4:
    <<: [ *logger, *common ]
    container_name: script-docker-4
    build:
      context: .
      dockerfile: ./Dockerfile
      args: 
        env_count: 4
    volumes:
      - ./scripts:/sripts_colle
      - ./env/all:/all
      - ./env/env4:/env
  script-docker-5:
    <<: [ *logger, *common ]
    container_name: script-docker-5
    build:
      context: .
      dockerfile: ./Dockerfile
      args: 
        env_count: 5
    volumes:
      - ./scripts:/sripts_colle
      - ./env/all:/all
      - ./env/env5:/env